set(_CATKIN_CURRENT_PACKAGE "tb_self_experimentation")
set(tb_self_experimentation_VERSION "0.0.0")
set(tb_self_experimentation_MAINTAINER "David Issa Mattos <davidis@chalmers.se>")
set(tb_self_experimentation_PACKAGE_FORMAT "1")
set(tb_self_experimentation_BUILD_DEPENDS "apriltags" "image_transport" "roscpp" "sensor_msgs" "geometry_msgs" "tf" "cv_bridge" "message_generation" "nodelet" "std_msgs" "cmake_modules" "using_markers" "visualization_msgs" "move_base_msgs" "actionlib" "libopencv-dev")
set(tb_self_experimentation_BUILD_EXPORT_DEPENDS "move_base_msgs" "actionlib" "using_markers" "visualization_msgs" "apriltags" "image_transport" "roscpp" "sensor_msgs" "geometry_msgs" "tf" "cv_bridge" "message_runtime" "nodelet" "std_msgs" "libopencv-dev")
set(tb_self_experimentation_BUILDTOOL_DEPENDS "catkin")
set(tb_self_experimentation_BUILDTOOL_EXPORT_DEPENDS )
set(tb_self_experimentation_EXEC_DEPENDS "move_base_msgs" "actionlib" "using_markers" "visualization_msgs" "apriltags" "image_transport" "roscpp" "sensor_msgs" "geometry_msgs" "tf" "cv_bridge" "message_runtime" "nodelet" "std_msgs" "libopencv-dev")
set(tb_self_experimentation_RUN_DEPENDS "move_base_msgs" "actionlib" "using_markers" "visualization_msgs" "apriltags" "image_transport" "roscpp" "sensor_msgs" "geometry_msgs" "tf" "cv_bridge" "message_runtime" "nodelet" "std_msgs" "libopencv-dev")
set(tb_self_experimentation_TEST_DEPENDS )
set(tb_self_experimentation_DOC_DEPENDS )
set(tb_self_experimentation_DEPRECATED "")