set(_CATKIN_CURRENT_PACKAGE "tb_simulation")
set(tb_simulation_VERSION "0.0.0")
set(tb_simulation_MAINTAINER "chalmers <chalmers@todo.todo>")
set(tb_simulation_PACKAGE_FORMAT "1")
set(tb_simulation_BUILD_DEPENDS )
set(tb_simulation_BUILD_EXPORT_DEPENDS )
set(tb_simulation_BUILDTOOL_DEPENDS "catkin")
set(tb_simulation_BUILDTOOL_EXPORT_DEPENDS )
set(tb_simulation_EXEC_DEPENDS )
set(tb_simulation_RUN_DEPENDS )
set(tb_simulation_TEST_DEPENDS )
set(tb_simulation_DOC_DEPENDS )
set(tb_simulation_DEPRECATED "")